volumes:
  grafana: {}
  prometheus: {}

services:

  prometheus:
    image: prom/prometheus:v3.5.0
    volumes:
    - prometheus:/prometheus
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: host
    restart: unless-stopped
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.listen-address=127.0.0.1:9090

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    network_mode: host
    environment:
      GF_SERVER_HTTP_ADDR: 127.0.0.1
      GF_SERVER_HTTP_PORT: "3000"
    volumes:
      - grafana:/var/lib/grafana

