volumes:
  grafana: {}
  prometheus: {}

services:

  prometheus:
    image: prom/prometheus:v3.5.0
    volumes:
    - prometheus:/prometheus
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: host
    restart: unless-stopped
    ports:
    - 9090:9090

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    network_mode: host
    ports:
      - '3000:3000'
    volumes:
      - grafana:/var/lib/grafana

