global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: gochat
    static_configs:
    - targets:
      - localhost:8008

  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:9090
